USE [InvoiceDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [PurchaseOrders](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PONo] [varchar](40) NOT NULL,
	[Amount] [int] NOT NULL
 CONSTRAINT [PK_PurchaseOrders_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


